{
  "swagger": "2.0",
  "info": {
    "title": "Store Appointments Booking API - DRAFT VERSION",
    "version": "1.0.0",
    "description": "API to book an apointment in a store\n\n# Relevant  Definitions and concepts\n\n* **Store**: A shop of any size or kind where you can buy many different types of goods or services or be assisted.\n* **Motive**: A motive to visit a shop. It can be some kind of service (TV, Internet, Movile, ...) a product, a terminal, support, etc.\n* **Slot**: A timed bounded period available in a store to attend a visitor for a given motive. A visitor must indicate a free slot to book an appointment.\n* **Reservation**: The temporal model to retrieve all information for booking an appointment. It contains the store, motive, slot and visitor information. Once confirmed it becomes an appointment booking.\n* **Booking**: Model that identifies the confirmed appointment booking.\n\n# API Functionality\n This API allows a visitor to book an appointment in a store. This API is related with store-appointments API as it can be used to search for a store.\n\nThe visitor journey to book an appointment includes the following steps:\n - Store selection. Store can be found through the store-appointments API\n - Motive of visit selection\n - Available slot selection\n - Complete visitor details (contact information, not user related)\n - Confirm the reservation\n\nOnce the booking is confirmed it can be canceled by the visitor at any time.\n\n# Resources and Operations overview\nResources for this API are **motives**, **slots**, **reservations** and **booking** to allow the visitor journey.\n- All resources can be readed.\n- Reservations can be also created, edited and canceled.\n- Bookings can also be deleted.\n\nResources in the API can be used in 2-legged or 3-legged mode.\n\n## Further Info and Support\n Find answers to Frequently Asked Questions in https://qna.baikalplatform.com/c/api-faq\n Topics with the **tag 'Store'** are specific for Store Finder or Store Appointments Booking APIs.",
    "termsOfService": "https://www.telefonica.es/es/",
    "contact": {
      "name": "4th Platform Team",
      "email": "4pf@tid.es"
    }
  },
  "x-fp-apiPrefix": "/store-appointments",
  "schemes": [
    "https"
  ],
  "host": "store-appointments:8080",
  "basePath": "/store-appointments/v1",
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "tags": [
    {
      "name": "motives",
      "description": "Operations related to store motives information"
    },
    {
      "name": "slots",
      "description": "Operations to get stores availability (time slots)"
    },
    {
      "name": "reservations",
      "description": "Operations to manage store reservation process"
    },
    {
      "name": "bookings",
      "description": "Operations to manage appointment bookings"
    }
  ],
  "x-fp-scopesDefinition": {
    "motives:read": "Allows you to look for motives information for a store",
    "slot:read": "Allows you to look for free time slots in a store",
    "reservation:read": "Allows you to retrive reservation information",
    "reservation:write": "Allows you to create or update a reservation in a store",
    "reservation:delete": "Allows you to delete a reservation in a store",
    "booking:read": "Allows you to get information for an appointment booking in a store",
    "booking:delete": "Allows you to delete an appointment booking in a store"
  },
  "paths": {
    "/stores/{store_id}/motives": {
      "get": {
        "tags": [
          "motives"
        ],
        "summary": "Gets motives of visit for a given store.",
        "description": "Gets motives of visit for a given store. The store_id can be obtained from store-finder API",
        "operationId": "fetchStoreMotives",
        "x-fp-scopes": [
          "motives:read"
        ],
        "parameters": [
          {
            "$ref": "https://docs.baikalplatform.com/common/v2.3/common.json#/parameters/x-correlator"
          },
          {
            "name": "store_id",
            "in": "path",
            "description": "Store Identifier",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "List of motives of visit for a store",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Motive"
              }
            }
          },
          "400": {
            "description": "Problem with the client request",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/InvalidArgument"
            },
            "examples": {
              "application/json": {
                "code": "INVALID_ARGUMENT",
                "message": "Client specified an invalid argument, request body or query param"
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/NotFound"
            },
            "examples": {
              "application/json": {
                "code": "NOT_FOUND",
                "message": "A specified resource is not found"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/Internal"
            },
            "examples": {
              "application/json": {
                "code": "INTERNAL",
                "message": "Server error"
              }
            }
          }
        }
      }
    },
    "/stores/{store_id}/motives/{motive_id}": {
      "get": {
        "tags": [
          "motives"
        ],
        "summary": "Fetches a motive information",
        "description": "Fetches a motive information.",
        "operationId": "fetchMotive",
        "x-fp-scopes": [
          "motives:read"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "x-correlator",
            "required": false,
            "description": "Correlation id for the different services",
            "type": "string"
          },
          {
            "name": "store_id",
            "in": "path",
            "description": "Store Identifier",
            "required": true,
            "type": "string"
          },
          {
            "name": "motive_id",
            "in": "path",
            "description": "Motive Identifier to optionally retrieve only slots valid to attend that motive in the store",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Motive details",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "#/definitions/Motive"
            }
          },
          "400": {
            "description": "Problem with the client request",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/InvalidArgument"
            },
            "examples": {
              "application/json": {
                "code": "INVALID_ARGUMENT",
                "message": "Client specified an invalid argument, request body or query param"
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/NotFound"
            },
            "examples": {
              "application/json": {
                "code": "NOT_FOUND",
                "message": "A specified resource is not found"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/Internal"
            },
            "examples": {
              "application/json": {
                "code": "INTERNAL",
                "message": "Server error"
              }
            }
          }
        }
      }
    },
    "/stores/{store_id}/slots/calendar": {
      "get": {
        "tags": [
          "slots"
        ],
        "summary": "Fetches all available slots for an appointment booking.",
        "description": "Fetches all available slots for appointment booking for a store, grouped by day.",
        "operationId": "fetchSlotsCalendar",
        "x-fp-scopes": [
          "slot:read"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "x-correlator",
            "required": false,
            "description": "Correlation id for the different services",
            "type": "string"
          },
          {
            "name": "store_id",
            "in": "path",
            "description": "Store Identifier",
            "required": true,
            "type": "string"
          },
          {
            "name": "motive_id",
            "in": "query",
            "description": "Motive Identifier",
            "required": true,
            "type": "string"
          },
          {
            "name": "start_date",
            "in": "query",
            "description": "The first day to get available slots from",
            "required": true,
            "type": "string",
            "format": "date"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Maximum number of days with available slots that *may* be returned starting from start_date.\nThis limit can be overriden by the service e.g. for performance reasons.\n",
            "required": false,
            "type": "integer",
            "format": "int32",
            "default": 7
          }
        ],
        "responses": {
          "200": {
            "description": "List of slots grouped by day.",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/DateSlots"
              }
            }
          },
          "400": {
            "description": "Problem with the client request",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/InvalidArgument"
            },
            "examples": {
              "application/json": {
                "code": "INVALID_ARGUMENT",
                "message": "Client specified an invalid argument, request body or query param"
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/NotFound"
            },
            "examples": {
              "application/json": {
                "code": "NOT_FOUND",
                "message": "A specified resource is not found"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/Internal"
            },
            "examples": {
              "application/json": {
                "code": "INTERNAL",
                "message": "Server error"
              }
            }
          }
        }
      }
    },
    "/reservations": {
      "post": {
        "tags": [
          "reservations"
        ],
        "summary": "Creates a reservation for a motive on a store",
        "description": "Creates a reservation for a motive on a store.\n",
        "operationId": "createReservation",
        "x-fp-scopes": [
          "reservation:write"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "x-correlator",
            "required": false,
            "description": "Correlation id for the different services",
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewReservation"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created reservation",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "#/definitions/Reservation"
            },
            "examples": {
              "application/json": {
                "reservation_id": "sdc7sdh-asd3234-dasdw",
                "store_id": "sdfsf-swer3wsdsf-42rwer",
                "motive_id": "123dsdf-23423wer-123213",
                "created_on": "2019-11-03T13:31:23.000Z",
                "expiration": "2019-11-03T13:36:23.000Z",
                "slot": {
                  "start": "2019-11-04T09:00:00.000Z",
                  "end": "2019-11-04T09:20:00.000Z"
                }
              }
            }
          },
          "400": {
            "description": "Problem with the client request",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/InvalidArgument"
            },
            "examples": {
              "application/json": {
                "code": "INVALID_ARGUMENT",
                "message": "Client specified an invalid argument, request body or query param"
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/NotFound"
            },
            "examples": {
              "application/json": {
                "code": "NOT_FOUND",
                "message": "A specified resource is not found"
              }
            }
          },
          "410": {
            "description": "Slot gone",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "#/definitions/SlotGoneError"
            },
            "examples": {
              "application/json": {
                "code": "STORE_APPOINTMENTS.SLOT_GONE",
                "message": "Slot is not available anymore. Conflict on reservation"
              }
            }
          },
          "429": {
            "description": "Too Many Requests",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/TooManyRequests"
            },
            "examples": {
              "application/json": {
                "code": "TOO_MANY_REQUESTS",
                "message": "The user has sent too many requests in a given amount of time"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/Internal"
            },
            "examples": {
              "application/json": {
                "code": "INTERNAL",
                "message": "Server error"
              }
            }
          }
        }
      }
    },
    "/reservations/{reservation_id}": {
      "get": {
        "tags": [
          "reservations"
        ],
        "summary": "Retrieves a reservation",
        "description": "Retrieves a reservation with all associated data available:\n  - Store\n - Motive\n - Slot\n - Visitor Details\n",
        "operationId": "fetchReservation",
        "x-fp-scopes": [
          "reservation:read"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "x-correlator",
            "required": false,
            "description": "Correlation id for the different services",
            "type": "string"
          },
          {
            "name": "reservation_id",
            "in": "path",
            "description": "Id of the reservation",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Reservation information",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          },
          "400": {
            "description": "Problem with the client request",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/InvalidArgument"
            },
            "examples": {
              "application/json": {
                "code": "INVALID_ARGUMENT",
                "message": "Client specified an invalid argument, request body or query param"
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/NotFound"
            },
            "examples": {
              "application/json": {
                "code": "NOT_FOUND",
                "message": "A specified resource is not found"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/Internal"
            },
            "examples": {
              "application/json": {
                "code": "INTERNAL",
                "message": "Server error"
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "reservations"
        ],
        "summary": "Deletes a reservation",
        "description": "Deletes a reservation.",
        "operationId": "deleteReservation",
        "x-fp-scopes": [
          "reservation:delete"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "x-correlator",
            "required": false,
            "description": "Correlation id for the different services",
            "type": "string"
          },
          {
            "name": "reservation_id",
            "in": "path",
            "description": "Id of the reservation",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Reservation deleted",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            }
          },
          "400": {
            "description": "Invalid format for identifier",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v1.0/errors.json#/definitions/InvalidArgument"
            }
          },
          "404": {
            "description": "Resource not found",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v1.0/errors.json#/definitions/NotFound"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v1.0/errors.json#/definitions/Internal"
            }
          }
        }
      }
    },
    "/reservations/{reservation_id}/visitor": {
      "put": {
        "tags": [
          "reservations"
        ],
        "summary": "Updates the reservation with visitor details",
        "description": "Updates the reservation with visitor details",
        "operationId": "updateReservationWithVisitorDetails",
        "x-fp-scopes": [
          "reservation:write"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "x-correlator",
            "required": false,
            "description": "Correlation id for the different services",
            "type": "string"
          },
          {
            "name": "reservation_id",
            "in": "path",
            "description": "Id of the reservation",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/VisitorDetails"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Reservation with updated visitor details updated",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "#/definitions/Reservation"
            }
          },
          "400": {
            "description": "Problem with the client request",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/InvalidArgument"
            },
            "examples": {
              "application/json": {
                "code": "INVALID_ARGUMENT",
                "message": "Client specified an invalid argument, request body or query param"
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/NotFound"
            },
            "examples": {
              "application/json": {
                "code": "NOT_FOUND",
                "message": "A specified resource is not found"
              }
            }
          },
          "429": {
            "description": "Too Many Requests",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/TooManyRequests"
            },
            "examples": {
              "application/json": {
                "code": "TOO_MANY_REQUESTS",
                "message": "The user has sent too many requests in a given amount of time"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/Internal"
            },
            "examples": {
              "application/json": {
                "code": "INTERNAL",
                "message": "Server error"
              }
            }
          }
        }
      }
    },
    "/reservations/{reservation_id}/confirm": {
      "post": {
        "tags": [
          "reservations"
        ],
        "summary": "Confirms a reservation and creates a booking for it",
        "description": "Confirms a reservation and creates a booking for it.",
        "operationId": "createBookingForReservation",
        "x-fp-scopes": [
          "reservation:write"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "x-correlator",
            "required": false,
            "description": "Correlation id for the different services",
            "type": "string"
          },
          {
            "name": "reservation_id",
            "in": "path",
            "description": "Id of the reservation",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Reservation confirmed and booking created",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "#/definitions/BookingConfirmation"
            }
          },
          "400": {
            "description": "Problem with the client request",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/InvalidArgument"
            },
            "examples": {
              "application/json": {
                "code": "INVALID_ARGUMENT",
                "message": "Client specified an invalid argument, request body or query param"
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/NotFound"
            },
            "examples": {
              "application/json": {
                "code": "NOT_FOUND",
                "message": "A specified resource is not found"
              }
            }
          },
          "429": {
            "description": "Too Many Requests",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/TooManyRequests"
            },
            "examples": {
              "application/json": {
                "code": "TOO_MANY_REQUESTS",
                "message": "The user has sent too many requests in a given amount of time"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/Internal"
            },
            "examples": {
              "application/json": {
                "code": "INTERNAL",
                "message": "Server error"
              }
            }
          }
        }
      }
    },
    "/bookings/{booking_id}": {
      "get": {
        "tags": [
          "bookings"
        ],
        "summary": "Fetches details for an appointment booking",
        "description": "Retrieves an appointment booking with all associated data available:\n  - Store\n - Motive\n - StartTime\n - Status\n",
        "operationId": "fetchBooking",
        "x-fp-scopes": [
          "booking:read"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "x-correlator",
            "required": false,
            "description": "Correlation id for the different services",
            "type": "string"
          },
          {
            "name": "booking_id",
            "in": "path",
            "description": "Id of the appointment booking",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Booking details",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          },
          "400": {
            "description": "Problem with the client request",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/InvalidArgument"
            },
            "examples": {
              "application/json": {
                "code": "INVALID_ARGUMENT",
                "message": "Client specified an invalid argument, request body or query param"
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/NotFound"
            },
            "examples": {
              "application/json": {
                "code": "NOT_FOUND",
                "message": "A specified resource is not found"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v2.0/errors.json#/definitions/Internal"
            },
            "examples": {
              "application/json": {
                "code": "INTERNAL",
                "message": "Server error"
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "bookings"
        ],
        "summary": "Deletes an appointment booking",
        "description": "Deletes an appointment booking so cancels the appointment or event",
        "operationId": "deleteBooking",
        "x-fp-scopes": [
          "booking:delete"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "x-correlator",
            "required": false,
            "description": "Correlation id for the different services",
            "type": "string"
          },
          {
            "name": "booking_id",
            "in": "path",
            "description": "Id of the appointment booking",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Booking deleted",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            }
          },
          "400": {
            "description": "Invalid format for identifier",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v1.0/errors.json#/definitions/InvalidArgument"
            }
          },
          "404": {
            "description": "Resource not found",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v1.0/errors.json#/definitions/NotFound"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "x-correlator": {
                "description": "Correlation id for the different services",
                "type": "string"
              }
            },
            "schema": {
              "$ref": "https://docs.baikalplatform.com/errors/v1.0/errors.json#/definitions/Internal"
            }
          }
        }
      }
    }
  },
  "x-fp-health": "http://store-appointments:8080/healthz",
  "definitions": {
    "Motive": {
      "type": "object",
      "description": "Motive of visit model",
      "required": [
        "motive_id",
        "name"
      ],
      "properties": {
        "motive_id": {
          "type": "string",
          "description": "Motive identifier"
        },
        "name": {
          "type": "string",
          "description": "Name of the motive of visit."
        }
      },
      "example": {
        "motive_id": "asdasd-asdasd-sdfsdf-231",
        "name": "Informaci√≥n y consulta"
      }
    },
    "DateSlots": {
      "type": "object",
      "description": "List of slots for a date",
      "required": [
        "date",
        "slots"
      ],
      "properties": {
        "date": {
          "type": "string",
          "description": "Date for the slot calendar",
          "format": "date"
        },
        "slots": {
          "type": "array",
          "description": "List of slots",
          "items": {
            "$ref": "#/definitions/Slot"
          }
        }
      },
      "example": {
        "date": "2019-11-03",
        "slots": [
          {
            "start": "2019-11-03T09:00:00.000Z",
            "end": "2019-11-03T09:20:00.000Z"
          },
          {
            "start": "2019-11-03T09:20:00.000Z",
            "end": "2019-11-03T09:40:00.000Z"
          }
        ]
      }
    },
    "Slot": {
      "type": "object",
      "description": "Period of time",
      "required": [
        "start",
        "end"
      ],
      "properties": {
        "start": {
          "type": "string",
          "description": "Start of a period of time, in ISO-8601 extended local date format. Time-offset from UTC may be used to match local OB time.",
          "format": "date-time"
        },
        "end": {
          "type": "string",
          "description": "End of a period of time, in ISO-8601 extended local date format. Time-offset from UTC may be used to match local OB time.",
          "format": "date-time"
        }
      },
      "example": {
        "start": "2019-11-03T09:00:00.000Z",
        "end": "2019-11-03T09:20:00.000Z"
      }
    },
    "NewReservation": {
      "type": "object",
      "description": "Model for creating a new reservation",
      "required": [
        "store_id",
        "motive_id",
        "start"
      ],
      "properties": {
        "store_id": {
          "type": "string",
          "description": "Store Identifier"
        },
        "motive_id": {
          "type": "string",
          "description": "Motive identifier"
        },
        "start": {
          "type": "string",
          "description": "Start of a time slot, in ISO-8601 extended local date format. Time-offset from UTC may be used to match local OB time.",
          "format": "date-time"
        }
      },
      "example": {
        "store_id": "sdfsf-swer3wsdsf-42rwer",
        "motive_id": "123dsdf-23423wer-123213",
        "start": "2019-11-04T09:00:00.000Z"
      }
    },
    "Reservation": {
      "type": "object",
      "description": "Reservation model. This model will become a booking when confirmed.",
      "required": [
        "reservation_id",
        "store_id",
        "motive_id",
        "slot"
      ],
      "properties": {
        "reservation_id": {
          "type": "string",
          "description": "Reservation Identifier"
        },
        "store_id": {
          "type": "string",
          "description": "Store Identifier"
        },
        "motive_id": {
          "type": "string",
          "description": "Motive identifier"
        },
        "created_on": {
          "type": "string",
          "description": "Reservation creation date",
          "format": "date-time",
          "example": "2019-05-30T06:10:00.000Z"
        },
        "expiration": {
          "type": "string",
          "description": "Expiration date time of the reservation.",
          "format": "date-time"
        },
        "slot": {
          "description": "Slot for the reservation",
          "$ref": "#/definitions/Slot"
        },
        "visitor_details": {
          "description": "Visitor details",
          "$ref": "#/definitions/VisitorDetails"
        }
      },
      "example": {
        "reservation_id": "sdc7sdh-asd3234-dasdw",
        "store_id": "sdfsf-swer3wsdsf-42rwer",
        "motive_id": "123dsdf-23423wer-123213",
        "created_on": "2019-11-03T13:31:23.000Z",
        "expiration": "2019-11-03T13:36:23.000Z",
        "slot": {
          "start": "2019-11-04T09:00:00.000Z",
          "end": "2019-11-04T09:20:00.000Z"
        },
        "visitor_details": {
          "first_name": "John",
          "last_name": "Doe",
          "email": "john.doe@gmail.com",
          "phone_number": "+34655555555",
          "notes": "I don't have data in my mobile line"
        }
      }
    },
    "VisitorDetails": {
      "type": "object",
      "description": "Details of a store visitor. This information is used to inform visitor about changes in the reservation",
      "required": [
        "first_name",
        "last_name",
        "email",
        "phone_number"
      ],
      "properties": {
        "first_name": {
          "type": "string",
          "description": "First name of the visitor"
        },
        "last_name": {
          "type": "string",
          "description": "Last name of the visitor"
        },
        "email": {
          "type": "string",
          "description": "Contact email of the visitor",
          "format": "email"
        },
        "phone_number": {
          "type": "string",
          "description": "Phone number for the visitor. E164 with + format."
        },
        "notes": {
          "type": "string",
          "description": "Free text"
        }
      },
      "example": {
        "first_name": "John",
        "last_name": "Doe",
        "email": "john.doe@gmail.com",
        "phone_number": "+34655555555",
        "notes": "I don't have data in my mobile line"
      }
    },
    "BookingConfirmation": {
      "type": "object",
      "description": "Confirmation of a reservation, returning the appointment booking id",
      "required": [
        "booking_id"
      ],
      "properties": {
        "booking_id": {
          "type": "string",
          "description": "Appointment booking Identifier"
        }
      },
      "example": {
        "booking_id": "asd3das-12sqweqdas-123qawed"
      }
    },
    "Booking": {
      "type": "object",
      "description": "Model that contains all information for an appointment booking",
      "required": [
        "booking_id",
        "store_id",
        "motive_id",
        "start",
        "status"
      ],
      "properties": {
        "booking_id": {
          "type": "string",
          "description": "Appoinment booking identifier"
        },
        "store_id": {
          "type": "string",
          "description": "Store Identifier"
        },
        "motive_id": {
          "type": "string",
          "description": "Motive identifier"
        },
        "start": {
          "type": "string",
          "description": "Start of a period of time, in ISO-8601 extended local date format. Time-offset from UTC may be used to match local OB time.",
          "format": "date-time"
        },
        "status": {
          "description": "Status of the appointment booking",
          "$ref": "#/definitions/BookingStatus"
        }
      },
      "example": {
        "booking_id": "sdfsf-swer3wsdsf-42rwer",
        "store_id": "fd5582d5-ef7a-4fa8-be84-602793f14497",
        "motive_id": "123dsdf-23423wer-123213",
        "start": "2019-11-03T09:00:00.000Z",
        "status": "ACTIVE"
      }
    },
    "BookingStatus": {
      "type": "string",
      "description": "Status of the appointment booking",
      "enum": [
        "ACTIVE",
        "CANCELLED"
      ],
      "example": "ACTIVE"
    },
    "SlotGoneError": {
      "allOf": [
        {
          "type": "object",
          "required": [
            "code"
          ],
          "properties": {
            "code": {
              "type": "string",
              "enum": [
                "STORE_APPOINTMENTS.SLOT_GONE"
              ],
              "default": "STORE_APPOINTMENTS.SLOT_GONE",
              "description": "Slot is not available anymore. Conflict on reservation."
            }
          }
        },
        {
          "$ref": "https://docs.baikalplatform.com/errors/v1.0/errors.json#/definitions/ModelError"
        }
      ]
    }
  }
}
